CITY_TIMEZONE = {
    "Phoenix": "America/Phoenix",
    "Nahariyya": "Asia/Jerusalem",
    "Dallas": "America/Chicago",
    "San Antonio": "America/Chicago",
    "Philadelphia": "America/New_York",
    "Los Angeles": "America/Los_Angeles",
    "Indianapolis": "America/Indiana/Indianapolis",
    "San Francisco": "America/Los_Angeles",
    "San Diego": "America/Los_Angeles",
    "Nashville": "America/Chicago",
    "Detroit": "America/Detroit",
    "Portland": "America/Los_Angeles",
    "Haifa": "Asia/Jerusalem",
    "Montreal": "America/Montreal",
    "Jerusalem": "Asia/Jerusalem",
    "Pittsburgh": "America/New_York",
    "Beersheba": "Asia/Jerusalem",
    "Chicago": "America/Chicago",
    "Toronto": "America/Toronto",
    "Vancouver": "America/Vancouver",
    "Tel Aviv District": "Asia/Jerusalem",
    "Atlanta": "America/New_York",
    "Las Vegas": "America/Los_Angeles",
    "Seattle": "America/Los_Angeles",
    "Kansas City": "America/Chicago",
    "Saint Louis": "America/Chicago",
    "Minneapolis": "America/Chicago",
    "Houston": "America/Chicago",
    "Jacksonville": "America/New_York",
    "Albuquerque": "America/Denver",
    "Miami": "America/New_York",
    "New York": "America/New_York",
    "Charlotte": "America/New_York",
    "Eilat": "Asia/Jerusalem",
    "Denver": "America/Denver",
    "Boston": "America/New_York"
}
